version: '3'
services: 
    db:
        image: 'postgres:latest'
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: appProjetoSdAPI
        volumes: 
            - ./pgdata:/varlib/postgresql/data
        networks:
            - postgres-compose-network
        ports: 
            - "5432:5432"

    teste-pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "juliana.batista@unifesspa.edu.br"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "16543:80"
        depends_on:
            - db
        networks:
            - postgres-compose-network
            
networks: 
    postgres-compose-network:
        driver: bridge